service: your-feed-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
